version: 2.1

defaults: &defaults
  resource_class: small
  docker:
    - image: circleci/node:14-buster
  working_directory: ~/sweater-comb
  environment:
    IMAGE: ghcr.io/snyk/sweater-comb

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sweater-comb
      - run:
          name: Install
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn tsc
      - run:
          name: Test
          command: yarn test
      - run:
          name: E2E Test
          command: ./end-end-tests/api-standards/test-bulk.bash

  docker-release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.7'
      - run:
          name: Build and push Docker image
          environment:
            GIT_BRANCH: << pipeline.git.branch >>
            GIT_TAG: << pipeline.git.tag >>
          command: |-
            [ -n "$IMAGE" ] || exit 1
            export TAG=${GIT_TAG:-${GIT_BRANCH}}
            [ -n "$TAG" ] || exit 1
            # Authenticate to OCI image repository
            echo "${GITHUB_TOKEN}" | docker login ghcr.io -u snyk --password-stdin
            # Build and push the just-built image
            set -x
            ./scripts/release-docker.bash

  npm-release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build and release
          command: ./scripts/build-npm.bash

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          name: Test
      - npm-release:
          name: NPM Release - Tag
          requires:
            - Test
          context: nodejs-app-release
          filters:
            branches:
              only: 'main'
  docker_publish:
    jobs:
      - docker-release:
          name: Docker Image Release
          filters:
            branches:
              ignore: '/.*/'
            tags:
              only: '/^v.*$/'
